"""geometries tablosuna previous_filename ekle

Revision ID: 55c068ebfb0f
Revises: c1e9a1a8e4d9
Create Date: 2026-08-20 20:49:57.951186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55c068ebfb0f'
down_revision: Union[str, Sequence[str], None] = 'c1e9a1a8e4d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geometries', sa.Column('previous_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('geometries', 'previous_filename')
    # ### end Alembic commands ###
